

all:
	$(MAKE) -C Linux_g++_binary_semaphore
	$(MAKE) -C Linux_g++_counting_semaphore
	$(MAKE) -C Linux_g++_delay_until
	$(MAKE) -C Linux_g++_dynamic_tasks
	$(MAKE) -C Linux_g++_dynamic_tasks_high_pri
	$(MAKE) -C Linux_g++_dynamic_tasks_multistart_scheduler_off
	$(MAKE) -C Linux_g++_dynamic_tasks_multistart_scheduler_on
	$(MAKE) -C Linux_g++_mutex_recursive
	$(MAKE) -C Linux_g++_mutex_standard
	$(MAKE) -C Linux_g++_queues_multiple_producers
	$(MAKE) -C Linux_g++_queues_multiple_producers_multiple_consumers
	$(MAKE) -C Linux_g++_queues_simple_producer_consumer
	$(MAKE) -C Linux_g++_read_write_lock_prefer_reader
	$(MAKE) -C Linux_g++_read_write_lock_prefer_writer
	$(MAKE) -C Linux_g++_simple_tasks
	$(MAKE) -C Linux_g++_task_delete
	$(MAKE) -C Linux_g++_tasklet_dtor
	$(MAKE) -C Linux_g++_tasklets
	$(MAKE) -C Linux_g++_tickhook_disable
	$(MAKE) -C Linux_g++_tickhooks
	$(MAKE) -C Linux_g++_timers
	$(MAKE) -C Linux_g++_unnamed_tasks
	$(MAKE) -C Linux_g++_workqueues
	$(MAKE) -C Linux_g++_workqueues_delete
	$(MAKE) -C null_g++

